[log]
logDir: ./log
logFile: signaling
# DEBUG INFO WARNING ERROR FATAL
# FATAL 请慎用，会导致进程退出
logLevel: DEBUG
logToStderr: true

#可自行定义
[http]
port: 8080
staticDir: ./static
staticPrefix: /static/

[https]
port: 8081
cert: ./conf/fullchain.pem
key: ./conf/privkey.pem

[xrpc.xrtc]
# 单位:ms
connectTimeout: 100
readTimeout: 500
writeTimeout: 500
server: 127.0.0.1:9000,127.0.0.1:9000